google:
    resource: "@googleBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_login:
    path:     /user/login
    defaults: { _controller: AppBundle:Security:login }

user_login_check:
    path:     /user/login/check
    defaults: { _controller: AppBundle:Security:check }

user_register:
    path:     /user/register
    defaults: { _controller: AppBundle:Registration:register }

user_confirmed:
    path:     /user/confirmed
    defaults: { _controller: AppBundle:Registration:confirmed }

user_dashboard:
    path:     /user/dashboard
    defaults: { _controller: AppBundle:Default:dashboard }