<?php

namespace googleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkerRepository extends EntityRepository
{
}
